# Generated by Django 2.1.2 on 2018-10-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('TECHNOLOGY', models.CharField(max_length=500)),
                ('PASSPORT_NUMBER', models.CharField(max_length=50)),
                ('ISSUED_DATE', models.DateField()),
                ('EXPIRY_DATE', models.DateField()),
                ('SALARY_ACCOUNT', models.CharField(max_length=50)),
                ('PRE_ORG_NAME', models.CharField(max_length=150)),
                ('TOT_EXP_YEARS', models.CharField(max_length=50)),
                ('TOT_EXP_MONTHS', models.CharField(max_length=50)),
                ('REL_EXP_YEARS', models.CharField(max_length=50)),
                ('REL_EXP_MONTHS', models.CharField(max_length=50)),
                ('PERSONAL_EMAIL', models.CharField(max_length=50)),
                ('BLOOD_GRP', models.CharField(max_length=50)),
                ('FAMILY_MEM', models.CharField(max_length=50)),
                ('MEM_NAME', models.CharField(max_length=50)),
                ('MEM_CON_NO', models.CharField(max_length=50)),
                ('CURR_ADDRESS', models.CharField(max_length=500)),
                ('PER_ADDRESS', models.CharField(max_length=500)),
                ('MARITAL_STS', models.CharField(max_length=50)),
            ],
        ),
    ]
