# Generated by Django 2.1.2 on 2018-10-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='email_design',
            table='Email_Information',
        ),
    ]
