# Generated by Django 2.1.2 on 2018-10-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0002_auto_20181023_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email_Design',
            new_name='Email_Information',
        ),
    ]
