# Generated by Django 2.1.2 on 2018-10-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0005_auto_20181023_1501'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='email_design',
            table='Email_Design',
        ),
    ]
