# Generated by Django 2.1.2 on 2018-10-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0007_auto_20181025_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_design',
            name='EXPIRY_DATE',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='email_design',
            name='ISSUED_DATE',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='email_design',
            name='MEM_CON_NO',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='email_design',
            name='REL_EXP_MONTHS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='email_design',
            name='REL_EXP_YEARS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='email_design',
            name='TOT_EXP_MONTHS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='email_design',
            name='TOT_EXP_YEARS',
            field=models.IntegerField(),
        ),
    ]
