# Generated by Django 2.1.2 on 2018-10-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0008_auto_20181025_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_design',
            name='CURR_ADDRESS',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='email_design',
            name='PER_ADDRESS',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='email_design',
            name='TECHNOLOGY',
            field=models.TextField(),
        ),
    ]
