# Generated by Django 2.1.2 on 2018-10-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0009_auto_20181025_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_design',
            name='MEM_CON_NO',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='email_design',
            name='PERSONAL_EMAIL',
            field=models.EmailField(max_length=254),
        ),
    ]
