# Generated by Django 2.1.2 on 2018-10-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0011_auto_20181025_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_information',
            name='SALARY_ACCOUNT',
            field=models.IntegerField(),
        ),
    ]
